backtrack/backtrack/urls.py
from django.urls import path
from django.conf.urls import url
from .views import PBIviews, projectViews, sprintViews, taskViews, homeViews
from django.shortcuts import redirect

urlpatterns = [
    # Home Path
    path('', homeViews.HomeView.as_view(), name='home'),

    # Paths for Product Backlog
    path('<int:pk>/pb/', PBIviews.ProductBacklogView.as_view(), name='pb'),
    path('<int:pk>/pb/add/', PBIviews.AddPBI.as_view(), name='add-pbi'),
    path('<int:pk>/pb/<int:pbipk>/update',
         PBIviews.updatePBI.as_view(), name='detail-pbi'),
    path('<int:pk>/pb/<int:pbipk>/delete',
         PBIviews.DeletePBI.as_view(), name='delete-pbi'),

    # Paths for Project (creation, invite members, send invite, accept invitation from team members)
    path('project/create', projectViews.CreateProject.as_view(),
         name='create-project'),
    path('project/create/<int:pk>/inviteList', projectViews.InviteMember.as_view(),
         name='invite-project-members'),
    path('<int:pk>/inviteAccept', projectViews.EmailMember.as_view(),
         name='email-member'),
    path('project/create/<int:pk>/add/developer', projectViews.AddDeveloper.as_view(),
         name='add-project-developer'),
    path('project/create/<int:pk>/add/manager', projectViews.AddManager.as_view(),
         name='add-project-manager'),
    path('<int:pk>/create/sprint',
         sprintViews.CreateSprint.as_view(), name='create-sprint'),

    # Tasks path in Product Backlog
    path('<int:pk>/<int:spk>/<int:pbipk>/add-task/',
         taskViews.AddTask.as_view(), name='add-task'),

    # Sprint paths
    path('<int:pk>/<int:spk>/',
         sprintViews.SprintDetail.as_view(), name='detail-sprint'),
    path('<int:pk>/pb/add-pbi-to-sprint',
         sprintViews.AddPBIToSprint.as_view(), name='add-pbi-to-sprint'),
    path('<int:pk>/<int:spk>/<int:pbipk>/remove-task/',
         sprintViews.RemovePBIfromSprint.as_view(), name='remove-pbi-from-sprint'),
    path('<int:pk>/<int:spk>/complete',
         sprintViews.CompleteSprint.as_view(), name='complete-sprint'),

    # Tasks paths in Sprint Backlog
    path('<int:pk>/<int:spk>/<int:taskpk>/detail-task/',
         taskViews.DetailTask.as_view(), name='detail-task'),
    path('task/in-progress', taskViews.AddTaskToInProgress.as_view(),
         name='task-in-progress'),
    path('task/done', taskViews.AddTaskToDone.as_view(), name='task-done'),
    path('task/not-done', taskViews.AddTaskToNotDone.as_view(), name='task-not-done'),
    path('<int:pk>/<int:spk>/<int:taskpk>/detail-task/delete-task/',
         taskViews.DeleteTask.as_view(), name='delete-task')
]

backtrack/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from backtrack import views
from django.shortcuts import redirect
from django.http import HttpResponseRedirect, HttpRequest
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('', lambda x: redirect('accounts/login')
         if not hasattr(HttpRequest, "user") else redirect('/home'), name='base'),
    path('home/', include('backtrack.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

backtrack/backtrack/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver
from django.urls import reverse
from django_fsm import FSMField, transition
from django.http import JsonResponse
# Create your models here.


class PBI(models.Model):
    status = FSMField(default='N')
    story_points = models.FloatField()
    effort_hours = models.FloatField()
    summary = models.TextField(default=None)
    priority = models.IntegerField(default=0)
    project = models.ForeignKey(
        'Project', on_delete=models.CASCADE, related_name='pbi')
    sprint = models.ForeignKey(
        'Sprint', on_delete=models.CASCADE, related_name='pbi', null=True, blank=True)

    @property
    def burndown(self):
        from django.db.models import Sum
        myDict = self.task.filter(
            status__exact="D").aggregate(Sum('effort_hours'))
        remainingHours = myDict['effort_hours__sum']
        if not remainingHours:
            remainingHours = 0
        return remainingHours

    @property
    def TotalTaskHours(self):
        from django.db.models import Sum
        myDict = self.task.all().aggregate(Sum('effort_hours'))
        taskHours = myDict['effort_hours__sum']
        if not taskHours:
            taskHours = 0
        return taskHours

    @property
    def remainingEffortHours(self):
        return self.effort_hours - self.burndown

    @transition(field=status, source=['N', 'U'], target='P')
    def addToSprint(self, sprint):
        self.sprint = sprint

    @transition(field=status, source='P', target='N')
    def removeFromSprint(self, sprint):
        self.sprint = None

    @transition(field=status, source='P', target='N')
    def markNotDone(self):
        pass

    @transition(field=status, source='P', target='D')
    def markDone(self):
        self.delete(transition=1)
        self.priority = 0

    @transition(field=status, source='P', target='U')
    def markUnfinished(self):
        self.sprint = None

    # can implement transition unfinished if need be

    def delete(self, *args, **kwargs):
        pbiList = self.project.pbi.all().exclude(status="D")
        for pbi in pbiList:
            if pbi.priority > self.priority:
                pbi.priority -= 1
                pbi.save()
        if not "transition" in kwargs:
            super().delete(*args, **kwargs)

    def __str__(self):
        return self.summary

    class Meta:
        db_table = "PBI"
        verbose_name = 'PBI'
        verbose_name_plural = 'PBIs'


class Project(models.Model):
    name = models.CharField(max_length=256, unique=True)
    complete = models.BooleanField(default=False)

    # Please add Dev Team through this method
    def add_dev_team(self, dev_team):
        # Put logic to not allow more than 9 team members (Not sure if correct)
        if self.projectParticipant.filter(role__exact="DT").user.count() >= 9:
            raise Exception("Too many developers")
        self.project_set.user = dev_team

    def __str__(self):
        return self.name

    class Meta:
        db_table = "Project"


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=1, choices=[(
        "D", "Developer"), ("M", "Manager")], default="D")

    def __str__(self):
        return self.user.username + "'s Profile"


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, created, **kwargs):
    if not created:
        instance.profile.save()


@receiver(pre_delete, sender=User)
def delete_user_profile(instance, **kwargs):
    instance.profile.delete()

    class Meta:
        db_table = "User Profile"


class ProjectParticipant(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="projectParticipant")
    role = models.CharField(max_length=2, choices=[(
        "SM", "Scrum Master"), ("PO", "Product Owner"), ("DT", "Development Team")])
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, related_name="projectParticipant")

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ['user', 'project']
        # permissions=[]
        # if role=="PO":
        #     permissions= ['can add PBI', 'can edit PBI']
        # else:
        #     permissions= []


class Sprint(models.Model):
    capacity = models.FloatField()
    project = models.ForeignKey(
        'Project', on_delete=models.CASCADE, related_name='sprint')
    start = models.DateField(
        auto_now=False, auto_now_add=False, blank=False)
    end = models.DateField(auto_now=False, auto_now_add=False, blank=False)
    complete = models.BooleanField(default=False)

    @property
    def notStarted(self):
        from datetime import date
        if date.today() >= self.start:
            return False
        return True

    @property
    def available(self):
        return not self.complete

    @property
    def remainingCapacity(self):
        from django.db.models import Sum
        myDict = self.pbi.all().aggregate(Sum('story_points'))
        usedCapacity = myDict['story_points__sum']
        if not usedCapacity:
            usedCapacity = 0
        return self.capacity - usedCapacity

    @property
    def count(self):
        return self.project.sprint.filter(start__lte=self.start).count()

    @property
    def remainingHours(self):
        from django.db.models import Sum
        # Get hours of all PBI that are not complete
        PBIList = self.pbi.all().exclude(status__exact="D")
        remainingHours = 0
        for PBI in PBIList:
            remainingHours += PBI.remainingEffortHours
        return remainingHours

    @property
    def remainingDays(self):
        from datetime import date
        if self.complete:
            return 0
        now = date.today()
        remDays = self.end - now
        if remDays.days < 0:
            return 0
        if remDays > self.end - self.start:
            return (self.end - self.start).days
        return remDays.days

    def get_absolute_url(self):
        return reverse("detail-sprint", kwargs={"pk": self.project_id, "spk": self.id})


class Task(models.Model):
    status = FSMField(default='N')
    effort_hours = models.FloatField()
    summary = models.TextField(default=None)
    pbi = models.ForeignKey(
        'PBI', on_delete=models.CASCADE, related_name='task')
    projectParticipant = models.ForeignKey(
        'ProjectParticipant', on_delete=models.CASCADE, related_name='task', null=True, blank=True)

    @transition(field=status, source='N', target='P')
    def putInProgress(self, pp):
        if self.projectParticipant:
            return True
        else:
            return False

    @transition(field=status, source='P', target='D')
    def putInDone(self):
        return True

    @transition(field=status, source='P', target='N')
    def putInNotDone(self):
        if self.projectParticipant:
            self.projectParticipant = None
        return True

    def __str__(self):
        return self.summary

    class Meta:
        db_table = "Task"


@receiver(post_save, sender=Task, dispatch_uid="complete_PBI")
def completePBI(sender, instance, **kwargs):
    if not instance.pbi.task.all().exclude(status__exact="D").exists():
        pbi = instance.pbi
        pbi.markDone()
        pbi.save()
        if not pbi.project.pbi.all().exclude(status__exact="D").exists():
            pbi.project.complete = True
            pbi.project.save()

backtrack/backtrack/views.py
from .models import PBI, Project
# from . import forms
from django.contrib.auth.models import User, Group
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.views.generic import TemplateView, FormView, CreateView, UpdateView, DeleteView
from collections import OrderedDict
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy


def getPBIfromProj(pk, all):
    from .models import PBI
    data, pbiList = [], PBI.objects.filter(Project_id=pk)
    for pbi in pbiList:
        obj = PBI.objects.get(pk=pbi.id)
        # If all is true then do not count objects with status done(which are finished), this is for when creating a new PBI
        if obj.status == "D" and (not bool(int(all))):
            continue
        else:
            data.append(obj)
    return data


class HomeView(LoginRequiredMixin, TemplateView):
    login_url = '/accounts/login'
    redirect_field_name = '/home'
    template_name = 'backtrack/home.html'

    def get_context_data(self, **kwargs):
        context = {}
        return context


class ProductBacklogView(LoginRequiredMixin, TemplateView):
    login_url = '/accounts/login'
    redirect_field_name = '/home'
    template_name = 'backtrack/pb.html'

    def get_context_data(self, **kwargs):
        import math
        # query = request.query_params
        data = getPBIfromProj(kwargs['pk'], self.request.GET['all'] if 'all' in self.request.GET else '0')
        data = sorted(data, key=lambda x: (
            x.priority if x.status != "D" else math.inf, x.summary))
        sum_effort_hours, sum_story_points = 0, 0
        for PBIObj in data:
            sum_effort_hours += PBIObj.effort_hours
            sum_story_points += PBIObj.story_points
            PBIObj.sum_effort_hours = sum_effort_hours
            PBIObj.sum_story_points = sum_story_points
        context = {'data': data}
        return context


class AddPBI(LoginRequiredMixin, CreateView):
    model = PBI
    fields = ['summary', 'story_points', 'effort_hours']
    login_url = '/accounts/login'
    redirect_field_name = '/home'
    template_name = "backtrack/addPBI.html"

    def get_success_url(self):
        return "{}?all=0".format(reverse('pb', kwargs={'pk': self.object.Project_id}))

    def form_valid(self, form):
        PBIData = getPBIfromProj(self.kwargs['pk'], '0')
        # Initialise Priority
        priority = 0
        # Sort According to Priority
        PBIData = sorted(PBIData, key=lambda x: (
            x.priority), reverse=True)
        # If no Item in list make priority 1
        if PBIData:
            priority = PBIData[0].priority + 1
        else:
            priority = 1
        form.instance.priority = priority
        form.instance.Project_id = self.kwargs['pk']
        return super().form_valid(form)


class updatePBI(LoginRequiredMixin, UpdateView):
    pk_url_kwarg = 'pbipk'
    kwargs = {'pk_url_kwarg': 'pbipk'}
    model = PBI
    fields = ['priority', 'summary', 'story_points', 'effort_hours']
    login_url = '/accounts/login'
    redirect_field_name = '/home'
    template_name = 'backtrack/PBIdetail.html'
    template_name_suffix = ''

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['PBI'] = self.object
        print(context)
        return context

    def get_success_url(self):
        return "{}?all=0".format(reverse('pb', kwargs={'pk': self.kwargs['pk']}))

    def form_valid(self, form):

        PBIList = getPBIfromProj(self.kwargs['pk'], '0')
        remove = []
        priorityData = form.cleaned_data['priority']
        if int(priorityData) < self.object.priority:
            # Remove all PBI with priority higher than post data priority
            # and lesser  or equal than current PBI priority
            for PBIObj in PBIList:
                if PBIObj.priority < int(priorityData) or PBIObj.priority >= self.object.priority:
                    remove.append(PBIObj.priority)
            PBIList = [
                PBIObj for PBIObj in PBIList if PBIObj.priority not in remove]
            # Increase each objects priority by one
            for PBIObj in PBIList:
                PBIObj.priority += 1
                PBIObj.save()
        else:
            # Remove all PBI with priority higher than post PBI priority
            # and lesser than and equal to Post data priority
            for PBIObj in PBIList:
                if PBIObj.priority <= self.object.priority or PBIObj.priority > int(priorityData):
                    remove.append(PBIObj.priority)
            PBIList = [
                PBIObj for PBIObj in PBIList if PBIObj.priority not in remove]
            # Decrease each objects priority by one
            for PBIObj in PBIList:
                PBIObj.priority -= 1
                PBIObj.save()

        return super().form_valid(form)


class DeletePBI(LoginRequiredMixin, DeleteView):
    model = PBI
    login_url = '/accounts/login'
    redirect_field_name = '/home'

    def get_success_url(self):
        return reverse_lazy('detail', kwargs={'pk': self.object.Project_id})

    def post(self, request, **kwargs):
        pbiList = getPBIfromProj(kwargs['pk'], '0')

        pbiToDel = get_object_or_404(PBI, pk=kwargs['pbipk'])

        for pbi in pbiList:
            if pbi.priority > pbiToDel.priority:
                pbi.priority -= 1
                pbi.save()

        pbiToDel.delete()
        return redirect("{}?all=0".format(reverse('pb', kwargs={'pk': kwargs['pk']})))

backtrack/backtrack/views/homeViews.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from ..helpers import addContext, getPBIfromProj

class HomeView(LoginRequiredMixin, TemplateView):
    login_url = '/accounts/login'
    template_name = 'backtrack/home.html'

    def get_context_data(self, **kwargs):
        if self.request.user.projectParticipant.filter(project__complete=False).exists():
            # If user has a project that is not yet completed
            context = {}
            # Add context variables for sidebar
            context = addContext(self, context)
        else:
            context = {}
            context['User'] = self.request.user
        return context

backtrack/backtrack/templates/backtrack/PBIdetail.html
{% extends "backtrack/base.html" %}
{% block content %}
<h1 class="page-header"><i class="fa fa-edit"></i> Edit </h1>
<div class="row placeholders"></div>
<form action={% url 'detail-pbi' pk=Project.id pbipk=PBI.id %} method="POST">
    {{ form.non_field_errors }}
    {% csrf_token %}
    {% if ProjectParticipant.role == "PO" %}
    <div class="form-group">
        {{form.priority.errors}}
        {{form.priority.label_tag}}
        {{form.priority}}
        <small id="priority-small-text" class="form-text text-muted">This is the Product Backlog Priority for this
            PBI</small>
    </div>
    {% endif %}
    <div class="form-group">
        {{form.summary.errors}}
        {{form.summary.label_tag}}
        {{form.summary}}
        <small id="priority-small-text" class="form-text text-muted">This is the summary for this PBI</small>
    </div>
    <div class="form-group">
        {{form.story_points.errors}}
        {{form.story_points.label_tag}}
        {{form.story_points}}
        <small id="priority-small-text" class="form-text text-muted">This is the Story Points for this PBI</small>
    </div>
    <div class="form-group">
        {{form.effort_hours.errors}}
        {{form.effort_hours.label_tag}}
        {{form.effort_hours}}
        <small id="priority-small-text" class="form-text text-muted">This is the Effort hours for this PBI</small>
    </div>
    {% if PBI.status == "N" or PBI.status == "U" %}
    {% if ProjectParticipant.role == "PO" %}
    <button type="submit" class="btn btn-primary" style="height:2.4em;width:5em;text-align:center;">Confirm</button>
    {% endif %}
    {% endif %}
</form>
{% if PBI.status == "N" or PBI.status == "U" %}
{% if ProjectParticipant.role == "PO" %}
<a id="Delete" href="{% url 'delete-pbi' pk=Project.id pbipk=PBI.id %}" type="submit" class="btn btn-danger"
    style="height:2.4em;width:5em;text-align: center; margin-top: 0.5em;">Delete</a>
{% endif %}
{% endif %}


{% if PBI.status == "N" and ProjectParticipant.role == "DT" or PBI.status == "U" and ProjectParticipant.role == "DT" %}
<form action="{% url 'add-pbi-to-sprint' pk=Project.id %}" method="post">
    {% csrf_token %}
    <input type="hidden" value="{{PBI.id}}" name="PBIs" />
    <button id="AddToSprint" type="submit" class="btn btn-primary"
        style="height:2.4em;width:10em;text-align: center; margin-top: 0.5em;">Add to Sprint</button>
</form>
{% endif %}

{% endblock content %}

backtrack/backtrack/templates/backtrack/Taskdetail.html
{% extends "backtrack/base.html" %}
{% block content %}
<h1 class="page-header"><i class="fa fa-edit"></i> Edit Task </h1>
<div class="row placeholders"></div>
<form action={% url 'detail-task' pk=Project.id spk=sprint.id taskpk=Task.id %} method="POST">
    {{ form.non_field_errors }}
    {% csrf_token %}
    <div class="form-group">
        {{form.summary.errors}}
        {{form.summary.label_tag}}
        {{form.summary}}
        <small id="priority-small-text" class="form-text text-muted">This is the summary for this Task</small>
    </div>
    {% if Task.pbi.TotalTaskHours < Task.pbi.effort_hours %}
    <div class="form-group">
        {{form.effort_hours.errors}}
        {{form.effort_hours.label_tag}}
        {{form.effort_hours}}
        <small id="priority-small-text" class="form-text text-muted">This is the Effort hours for this Task</small>
    </div>
    {% else %}
    <div class="form-group hidden-display">
        {{form.effort_hours.errors}}
        {{form.effort_hours.label_tag}}
        {{form.effort_hours}}
        <small id="priority-small-text" class="form-text text-muted">This is the Effort hours for this Task</small>
    </div>
    {% endif %}
    <div class="form-group">
        {{form.projectParticipant.errors}}
        <label for="id_projectParticipant">
            User:</label>
        {{ form.projectParticipant }}
        <small id="priority-small-text" class="form-text text-muted">This is the Project participant responsible for
            this Task</small>
    </div>
    {% if Task.status == 'N' and sprint.available %}
    <button type="submit" class="btn btn-primary">Confirm</button>
    {% endif %}
</form>
{% csrf_token %}
{% if Task.status == "N" and sprint.available %}
<a id="Delete" href="{% url 'delete-task' pk=Project.id spk=sprint.id taskpk=Task.id %}" type="submit"
    class="btn btn-danger" style="height:2.4em;width:5em;text-align: center; margin-top: 0.5em;">Delete</a>
{% endif %}

<form action={% url 'task-in-progress' %} method="POST">
    {% csrf_token %}
    {% if Task.status == 'N' and sprint.available %}
    <input type="hidden" value={{Task.id}} name='Task' />
    <input type="hidden" value={{Project.id}} name="ProjectID" />
    <input type="hidden" value={{sprint.id}} name="SprintID" />
    {% if ProjectParticipant.role == "DT" and ProjectParticipant.user.username == Task.projectParticipant.user.username %}
    <button type="submit" class="btn btn-primary" style="margin-top: 0.5em;">Start Task</button>
    {% endif %}
    {% endif %}
</form>

{% if Task.status == 'P' and sprint.available %}
<form action={% url 'task-done' %} method="POST">
    {% csrf_token %}
    <input type="hidden" value={{Task.id}} name='Task' />
    <input type="hidden" value={{Project.id}} name="ProjectID" />
    <input type="hidden" value={{sprint.id}} name="SprintID" />
    {% if ProjectParticipant.role == "DT" and ProjectParticipant.user.username == Task.projectParticipant.user.username %}
    <button type="submit" class="btn btn-primary" style="margin-top: 0.5em;">Finish Task</button>
    {% endif %}
</form>
<form action={% url 'task-not-done' %} method="POST">
    {% csrf_token %}
    <input type="hidden" value={{Task.id}} name='Task' />
    <input type="hidden" value={{Project.id}} name="ProjectID" />
    <input type="hidden" value={{sprint.id}} name="SprintID" />
    {% if ProjectParticipant.role == "DT" and ProjectParticipant.user.username == Task.projectParticipant.user.username %}
    <button type="submit" class="btn btn-primary" style="margin-top: 0.5em;">Task Not Done</button>
    {% endif %}
</form>
{% endif %}
{% endblock content %}

backtrack/backtrack/templates/backtrack/addPBI.html
{% extends "backtrack/base.html" %}
{% block content %}
    <h1 class="page-header"><i class="fa fa-plus" id="A"></i> Add </h1>
    <div class="row placeholders"></div>
    <form action={% url 'add-pbi' pk=Project.id %} method="POST">
        {{ form.non_field_errors }}
        {% csrf_token %}
       <div class="form-group">
            {{form.summary.errors}}
            {{form.summary.label_tag}}
            {{form.summary}}
           <small id="priority-small-text" class="form-text text-muted">This is the summary for this PBI</small>
       </div>
       <div class="form-group">
            {{form.story_points.errors}}
            {{form.story_points.label_tag}}
            {{form.story_points}}
           <small id="priority-small-text" class="form-text text-muted">This is the Story Points for this PBI</small>
       </div>
       <div class="form-group">
            {{form.effort_hours.errors}}
            {{form.effort_hours.label_tag}}
            {{form.effort_hours}}
           <small id="priority-small-text" class="form-text text-muted">This is the Effort hours for this PBI</small>
       </div>
       <button type="submit" class="btn btn-primary">Confirm</button>
    </form>
{% endblock content %}

backtrack/backtrack/templates/backtrack/createProject.html
{% extends "backtrack/base.html" %}
{% block content %}
<h1 class="page-header"><i class="fa fa-plus" id="A"></i> Add </h1>
<div class="row placeholders"></div>
<form action={% url 'create-project' %} method="POST">
    {{ form.non_field_errors }}
    {% csrf_token %}
    <div class="form-group">
        {{form.name.errors}}
        {{form.name.label_tag}}
        {{form.name}}
        <small id="priority-small-text" class="form-text text-muted">This is the name for the project</small>
    </div>
    <button type="submit" class="btn btn-primary">Confirm</button>
</form>
{% endblock content %}

backtrack/backtrack/templates/backtrack/createSprint.html
{% extends "backtrack/base.html" %}
{% block content %}
<h1 class="page-header"><i class="fa fa-plus" id="A"></i> Add </h1>
{% if messages %}
<ul class="messages" style="padding:0;">
    {% for message in messages %}
    <div class="alert alert-danger alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %} style="list-style:none">{{ message }}</li>
            {% endfor %}
    </div>

</ul>
{% endif %}
<div class="row placeholders"></div>
<form action={% url 'create-sprint' pk=Project.id %} method="POST">
    {{ form.non_field_errors }}
    {% csrf_token %}
    <div class="form-group">
        {{form.capacity.errors}}
        {{form.capacity.label_tag}}
        {{form.capacity}}
        <small id="priority-small-text" class="form-text text-muted">This is the capacity for the sprint</small>
    </div>
    <div class="form-group">
        {{form.start.errors}}
        {{form.start.label_tag}}
        {{form.start}}
        <small id="priority-small-text" class="form-text text-muted">This is the start date for the sprint</small>
    </div>
    <div class="form-group">
        {{form.end.errors}}
        {{form.end.label_tag}}
        {{form.end}}
        <small id="priority-small-text" class="form-text text-muted">This is the end date for the sprint</small>
    </div>
    <button type="submit" class="btn btn-primary">Confirm</button>
</form>
{% endblock content %}

backtrack/backtrack/templates/backtrack/home.html
{% extends "backtrack/base.html" %}
{% block content %}
<h1 class="page-header"><i class="fa fa-home"></i> Home </h1>
<ul class="messages" style="padding:0;">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %} style="list-style:none">{{ message }}</li>
            {% endfor %}
    </div>

    {% endif %}
</ul>
<div class="row placeholders"></div>
<h1 id="X">Hello {{user.first_name}} !</h1>
<h2>Welcome to your collaboration home.</h2>
{% if ProjectParticipant %}
<h3 style="text-align: center;">You are currently working as a
    {% if ProjectParticipant.role == "PO" %} 
    Product Owner
    {% elif ProjectParticipant.role == "DT" %}
    Development Team Member
    {% else %}
    Manager
    {% endif %}
    on Project : {{Project.name}}
</h3>
{% endif %}
{% if not Project and User.profile.role == "D"%}
<h3 style="text-align:center;margin-top:3rem;">Start a Project Now!</h3>
<div style="text-align:center;margin-top:2rem;">
    <a type="button" id="myButton" href={% url 'create-project' %} class="btn btn-primary">Start Project</a>
</div>
{% endif %}

<script>
    $(document).ready(function () {
        if (localStorage.getItem("Message")) {
            console.log("Here")
            var msg = localStorage.getItem("Message")
            $("ul.messages").append(
                '<div class="alert alert-success alert-dismissible"> <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a> <li class = "error" style = "list-style:none" > ' +
                msg + '</li> </div>')
            localStorage.clear();
        }
    })
</script>

{% endblock content %}

backtrack/backtrack/templates/backtrack/pbi_confirm_delete.html
{% extends "backtrack/base.html" %}
{% block content %}
<span style="text-align: center; margin: auto;">
    <form method="post">{% csrf_token %}
        <h4>Are you sure you want to delete "{{ object }}"?</h4>
        <input type="submit" value="Confirm" class="btn btn-danger">
    </form>
</span>
{% endblock content %}